### ISSUE TITLE
Invalid GraphQL Name

### ISSUE THREAD

**Issue by rich-coe** [KyleU/databaseflow#6]
- select GraphQL from db connection
- web page displays 'transmitting ...'  graphic
- error reported on startup window
- as far as I can tell the regex it is complaining about not matching does satisify the specified table name
    play.api.UnexpectedException: Unexpected exception[IllegalArgumentException: Name 'MLOG$_Q_RUN_OBJ_T' is not valid GraphQL name! Valid name should satisfy following regex: /^[_a-zA-Z][_a-zA-Z0-9]*$/.]
        at sangria.schema.Named$.checkName(Schema.scala:121)
        at sangria.schema.ObjectType$.apply(Schema.scala:237)
        at services.explore.ExploreTableHelper$.$anonfun$getTables$10(ExploreTableHelper.scala:42)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at services.explore.ExploreTableHelper$.getTables(ExploreTableHelper.scala:41)
        at services.explore.ExploreService$.exploreType(ExploreService.scala:16)
        at models.connection.ConnectionGraphQL$.queryFieldsForConnection(ConnectionGraphQL.scala:35)
        at models.graphql.ConnectionGraphQLSchema.<init>(ConnectionGraphQLSchema.scala:11)
        at services.graphql.GraphQLService.$anonfun$getConnectionSchema$1(GraphQLService.scala:43)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
        at services.graphql.GraphQLService.getConnectionSchema(GraphQLService.scala:41)
        at services.graphql.GraphQLService.execute(GraphQLService.scala:61)
        [....]

**Comment by KyleU** [comment]
Yeah, that table name is a problem. I'll strip out weird characters, thanks for the report!

**Comment by KyleU** [comment]
Fixed, thanks. I'll publish a new release now
