### ISSUE TITLE
[Bug] java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by xialvjun** [KyleU/databaseflow#7]
```bash
[xialvjun@xialvjun-linux bin]$ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)

[xialvjun@xialvjun-linux bin]$ java -jar DatabaseFlow.jar 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/xialvjun/bin/DatabaseFlow.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] 22:25:24.269 a.e.s.Slf4jLogger: Slf4jLogger started
[info] 22:25:25.280 s.ApplicationContext: Database Flow is starting.
[info] 22:25:25.300 s.ConfigFileService: File service initialized, using [/home/xialvjun/.databaseflow] as home directory.
[info] 22:25:25.526 s.ResultCacheDatabase: Result Cache database started as user [databaseflow] against url [jdbc:h2:/home/xialvjun/.databaseflow/result-cache].
[info] 22:25:25.549 s.MasterDatabase: Database Flow Storage database started as user [databaseflow] against url [jdbc:h2:/home/xialvjun/.databaseflow/databaseflow].
[warn] 22:25:26.109 s.ApplicationContext: Database Flow started.
[warn] 22:25:26.109 s.ApplicationContext:  - Head to http://localhost:4260 to get started!
[info] 22:25:26.121 s.MetricsServletActor: Reporting metrics over JMX.
[info] 22:25:26.136 s.MetricsServletActor: Starting metrics servlet at [http://0.0.0.0:4261/].
[info] 22:25:26.170 play.api.Play: Application started (Prod)
[info] 22:25:26.483 p.c.s.s.FakeKeyStore: Generating HTTPS key pair in /home/xialvjun/bin/conf/generated.keystore - this may take some time. If nothing happens, try moving the mouse/typing on the keyboard to generate some entropy.
[info] 22:25:27.722 s.VersionService: You are currently running the latest version of Database Flow.
[info] 22:25:28.579 s.RequestHandler: Request from [0:0:0:0:0:0:0:1]: GET /
[info] 22:25:28.736 s.LoggingFilter: 303 (138ms): GET /
Uncaught error from thread [databaseflow-akka.actor.default-dispatcher-3]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[databaseflow]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:741)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:95)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:414)
	at play.api.mvc.CookieBaker.encodeAsCookie$(Cookie.scala:413)
	at play.api.mvc.DefaultSessionCookieBaker.encodeAsCookie(Session.scala:95)
	at play.api.mvc.Result.$anonfun$bakeCookies$2(Results.scala:297)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Result.bakeCookies(Results.scala:296)
	at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:227)
	at play.core.server.AkkaHttpServer.$anonfun$executeAction$3(AkkaHttpServer.scala:302)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:49)
	at scala.concurrent.Promise.complete$(Promise.scala:48)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 42 more
[error] 22:25:28.926 a.a.ActorSystemImpl: Uncaught error from thread [databaseflow-akka.actor.default-dispatcher-3]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[databaseflow]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:741)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:95)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:414)
	at play.api.mvc.CookieBaker.encodeAsCookie$(Cookie.scala:413)
	at play.api.mvc.DefaultSessionCookieBaker.encodeAsCookie(Session.scala:95)
	at play.api.mvc.Result.$anonfun$bakeCookies$2(Results.scala:297)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Result.bakeCookies(Results.scala:296)
	at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:227)
	at play.core.server.AkkaHttpServer.$anonfun$executeAction$3(AkkaHttpServer.scala:302)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at play.api.libs.streams.Execution$trampoline$.executeScheduled(Execution.scala:109)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:49)
	at scala.concurrent.Promise.complete$(Promise.scala:48)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:38)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 42 common frames omitted

[xialvjun@xialvjun-linux bin]$ 
```

**Comment by KyleU** [comment]
Tried the latest release with Java 10, didn't encounter your error. Are you using v1.1.5, from the Github releases page?

**Comment by xialvjun** [comment]
No, I don't know the version. But I download it from https://databaseflow.com/ in 2018-05-29. My OS is ArchLinux.

**Comment by KyleU** [comment]
Try downloading again, it now redirects to the github release page. The
website version was out of date, thanks for bringing this to my attention!

**Comment by xialvjun** [comment]
Redownloaded it from https://github.com/KyleU/databaseflow/releases the first one: v1.1.5

Still that error:
```bash
Uncaught error from thread [databaseflow-akka.actor.default-dispatcher-2]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[databaseflow]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
```

```bash
[xialvjun@xialvjun-pc bin]$ sha256sum DatabaseFlow.jar 
e263563c7d4be7b0f79fec47e8fa4b912f944ebdcb95e312a71125351850bcb4  DatabaseFlow.jar
[xialvjun@xialvjun-pc bin]$
```

And tried again with `v1.1.1`:
```bash
[xialvjun@xialvjun-pc Download]$ sha256sum DatabaseFlow.jar 
b68e2d4026e8ec5d6e034058944b0db4e4ce0a296bc3fbc563a94e10eaab89ac  DatabaseFlow.jar
[xialvjun@xialvjun-pc Download]$

// The same error:
Uncaught error from thread [databaseflow-akka.actor.default-dispatcher-2]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[databaseflow]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
```

My OS is `archlinux` with jdk `pacman -S jdk10-openjdk`

**Comment by KyleU** [comment]
Very odd, I've tried on Linux JDK 10, still with no issue. Would you mind cloning the repo, and executing "sbt run", and letting me know if that works?

**Comment by KyleU** [comment]
Resolved with latest Play version, sorry for delay, it had to be fixed upstream
