### ISSUE TITLE
Testing on InformixDB

### ISSUE THREAD

**Issue by thebetterjort** [KyleU/databaseflow#9]
Error loading database (SchemaLoadError): Method not supported : IfxSqliConnect.getSchema()

**Comment by thebetterjort** [comment]
```
[warn] 10:57:45.347 u.ExceptionUtils$: Error [SchemaLoadError] encountered of type [SQLException].
java.sql.SQLException: Method not supported : IfxSqliConnect.getSchema()
	at com.informix.util.IfxErrMsg.getSQLException(Unknown Source)
	at com.informix.jdbc.IfxSqliConnect.getSchema(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getSchema(HikariProxyConnection.java)
	at services.schema.SchemaHelper$.$anonfun$calculateSchema$1(SchemaHelper.scala:11)
	at services.database.DatabaseConnection.withConnection(DatabaseConnection.scala:75)
	at services.schema.SchemaHelper$.calculateSchema(SchemaHelper.scala:8)
	at services.schema.SchemaService$.$anonfun$getSchema$1(SchemaService.scala:32)
	at scala.util.Try$.apply(Try.scala:213)
	at services.schema.SchemaService$.getSchema(SchemaService.scala:24)
	at services.socket.StartHelper.$anonfun$refreshSchema$3(StartHelper.scala:53)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[info] 10:57:50.797 u.w.RequestHandler: Request from [127.0.0.1]: GET /c/new

```

**Comment by KyleU** [comment]
I tried to get a local Informix running, but they make it hard to get running. I was counting on the JDBC interface smoothing out the bumps, but that clearly didn't work. Without a server to connect to, I instead removed Informix from the list of supported database engines :(
